server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

  location /api/ {
    proxy_read_timeout 900s;
    proxy_send_timeout 900s;
    proxy_pass http://backend:${LISTINGO_PORT};
  }

  location /files/ {
    proxy_pass http://backend:${LISTINGO_PORT};
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
