"""initial_schema

Revision ID: dca93ecfbff1
Revises: 
Create Date: 2026-07-17 10:57:23.375503
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dca93ecfbff1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_code'), 'prompt', ['code'], unique=True)
    op.create_table('provider',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('capability', sa.String(length=20), nullable=False),
    sa.Column('adapter', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('model_name', sa.String(length=160), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_capability'), 'provider', ['capability'], unique=False)
    op.create_index(op.f('ix_provider_code'), 'provider', ['code'], unique=True)
    op.create_table('workflow',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_code'), 'workflow', ['code'], unique=True)
    op.create_table('prompt_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prompt_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_version_prompt_id'), 'prompt_version', ['prompt_id'], unique=False)
    op.create_table('workflow_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('graph_json', sa.Text(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_version_workflow_id'), 'workflow_version', ['workflow_id'], unique=False)
    op.create_table('generation_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('asset_ids_json', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('prompt_version_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_version_id', sa.String(length=36), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_version.id'], ),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_job_status'), 'generation_job', ['status'], unique=False)
    op.create_table('generation_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('route_symbol', sa.String(length=12), nullable=False),
    sa.Column('image_type', sa.String(length=120), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_item_job_id'), 'generation_item', ['job_id'], unique=False)
    op.create_index(op.f('ix_generation_item_status'), 'generation_item', ['status'], unique=False)
    op.create_table('execution_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('node', sa.String(length=80), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('request_summary', sa.Text(), nullable=False),
    sa.Column('response_summary', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['generation_item.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['generation_job.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_log_created_at'), 'execution_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_execution_log_item_id'), 'execution_log', ['item_id'], unique=False)
    op.create_index(op.f('ix_execution_log_job_id'), 'execution_log', ['job_id'], unique=False)
    op.create_index(op.f('ix_execution_log_node'), 'execution_log', ['node'], unique=False)
    op.create_index(op.f('ix_execution_log_provider_id'), 'execution_log', ['provider_id'], unique=False)
    op.create_index(op.f('ix_execution_log_status'), 'execution_log', ['status'], unique=False)
    op.create_table('generation_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['generation_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_version_item_id'), 'generation_version', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_version_item_id'), table_name='generation_version')
    op.drop_table('generation_version')
    op.drop_index(op.f('ix_execution_log_status'), table_name='execution_log')
    op.drop_index(op.f('ix_execution_log_provider_id'), table_name='execution_log')
    op.drop_index(op.f('ix_execution_log_node'), table_name='execution_log')
    op.drop_index(op.f('ix_execution_log_job_id'), table_name='execution_log')
    op.drop_index(op.f('ix_execution_log_item_id'), table_name='execution_log')
    op.drop_index(op.f('ix_execution_log_created_at'), table_name='execution_log')
    op.drop_table('execution_log')
    op.drop_index(op.f('ix_generation_item_status'), table_name='generation_item')
    op.drop_index(op.f('ix_generation_item_job_id'), table_name='generation_item')
    op.drop_table('generation_item')
    op.drop_index(op.f('ix_generation_job_status'), table_name='generation_job')
    op.drop_table('generation_job')
    op.drop_index(op.f('ix_workflow_version_workflow_id'), table_name='workflow_version')
    op.drop_table('workflow_version')
    op.drop_index(op.f('ix_prompt_version_prompt_id'), table_name='prompt_version')
    op.drop_table('prompt_version')
    op.drop_index(op.f('ix_workflow_code'), table_name='workflow')
    op.drop_table('workflow')
    op.drop_index(op.f('ix_provider_code'), table_name='provider')
    op.drop_index(op.f('ix_provider_capability'), table_name='provider')
    op.drop_table('provider')
    op.drop_index(op.f('ix_prompt_code'), table_name='prompt')
    op.drop_table('prompt')
    op.drop_table('asset')
    # ### end Alembic commands ###

